# Configuration showing multiple AI providers for translation
# This demonstrates using different providers simultaneously

audio:
  sample_rate: 16000
  chunk_duration: 3.0
  device_index: null

transcription:
  model_size: "tiny"
  language: null

output:
  show_timestamps: true
  show_confidence: true

display:
  rich_ui: false
  show_stats: false

hooks:
  enabled: true
  hooks:
    # OpenAI direct - GPT-3.5 Turbo
    - type: "openai_translation"
      enabled: true
      config:
        api_key: "${OPENAI_API_KEY}"
        target_language: "Chinese"
        model: "gpt-3.5-turbo"
        max_tokens: 1000
        temperature: 0.3
        print_translation: true
        output_prefix: ""  # Optional prefix for translations
    
    # OpenRouter - Claude 3.5 Sonnet (disabled by default)
    - type: "openai_translation"
      enabled: false
      config:
        api_key: "${OPENROUTER_API_KEY}"
        base_url: "https://openrouter.ai/api/v1"
        target_language: "Chinese"
        model: "anthropic/claude-3.5-sonnet"
        max_tokens: 1000
        temperature: 0.3
        print_translation: true
        output_prefix: ""  # Optional prefix for translations
    
    # OpenRouter - GPT-4 (disabled by default)
    - type: "openai_translation"
      enabled: false
      config:
        api_key: "${OPENROUTER_API_KEY}"
        base_url: "https://openrouter.ai/api/v1"
        target_language: "Chinese"
        model: "openai/gpt-4"
        max_tokens: 1000
        temperature: 0.3
        print_translation: true
        output_prefix: ""  # Optional prefix for translations
    
    # Console log for comparison
    - type: "console_log"
      enabled: true
      config:
        show_confidence: true