# Configuration for OpenRouter translation hook
# OpenRouter provides access to multiple AI models through a single API
# Sign up at https://openrouter.ai/ to get your API key

audio:
  sample_rate: 16000
  chunk_duration: 3.0
  device_index: null

transcription:
  model_size: "tiny"
  language: null

output:
  show_timestamps: true
  show_confidence: true

display:
  rich_ui: false
  show_stats: false

hooks:
  enabled: true
  hooks:
    # OpenRouter translation hook - translates to Chinese
    - type: "openai_translation"
      enabled: true
      config:
        api_key: "${OPENROUTER_API_KEY}"  # Set: export OPENROUTER_API_KEY=sk-or-v1-...
        base_url: "https://openrouter.ai/api/v1"
        target_language: "Chinese"
        model: "openai/gpt-3.5-turbo"  # OpenRouter model format
        max_tokens: 1000
        temperature: 0.3
        print_translation: true
        output_prefix: ""  # Optional prefix for translations (e.g., "🤖", "AI:", etc.)
    
    # Console log for comparison
    - type: "console_log"
      enabled: true
      config:
        show_confidence: true
    
    # Log translations to file
    - type: "file_append"
      enabled: true
      config:
        file_path: "openrouter-translations.log"
        format: "Original: {text}"
